services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./.env
  #
  #application:
  #  image: python:latest
  #  ports:
  #    - 80:80
  #  env_file: "./.env"